name: NPM Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  update-nodered:
    runs-on: ubuntu-latest
    needs: [publish-npm]
    steps:
      - uses: Hacksore/node-red-flow@v2
        with:
          repo: node-red-contrib-google-smarthome
